Learn Computer Programming -*- mode: org -*-

* Welcome!

Welcome to my website dedicated to all people everywhere who are interested
in learning computer programming. This is a passion of mine, and I want to
learn with you and from you, and share with you ways you can:

1. Learn computer programming
2. Monetize computer programming as a hobby, side job, or even a career.

* Motivation

Why learn computer programming? Because you are interested in ...

1. Additional income. The finacial incentive here is huge. Computer programming is one of the highest-paying industries today. See some [[https://money.usnews.com/careers/best-jobs/computer-programmer/salary][2017 data]] on computer programmer compensation in the U.S. Also, here is some [[https://www.bls.gov/ooh/computer-and-information-technology/computer-programmers.htm][data]] from the U.S. Bureau of Labor Statistics.
2. A flexible job. Computer programmers can work from any place where they have access to a computer network, and they can generally set their own hours.
3. Saving time and effort. Often, mind-numbing and repetitive tasks on a computer can be automated. This saves time and energy, and eliminates human fatigue along with associated human errors. When tasks are automated, humans are liberated to perform other tasks that are not so easily automated. Productivity is increased, and the cost of labor for automated tasks is saved. Tasks that could be automated can be as simple as renaming several photos in a consistent way or finding and deleting duplicate photos in your photo library. Personally, I've saved thousands of person-hours of labor by automating the collection, analysis, and visualizing scientific data, and I've taught others to do the same. Another interesting application of computer automation is algorithmic trading. Here, computer-savvy investors write programs to monitor market conditions. Certain conditions trigger buy or sell events for certain stocks. Having systematized trading in this manner, the trader is now unbudened from closely monitoring the market, and finds the freedom to do other things.
4. A beautiful and fun life-long mental exercise and discipline. I think of computer programming as an art and science of solving problems logically, and in a robust manner. I find few tasks as satisfying as writing smart, reusable code which accomplishes a task effectively and robustly. This is a fun exercise that can change the way you approach problems in all areas of life, as computer programming is an exercise in applied logic and problem-solving.
Let us now further motivate your interests in computer programming,
as well as uncover some of your personal interests and goals here so
that you may better guide your learning and exploration into the world of
computer programming. To do this, I have compiled for you some videos
that you can watch to help you think about how you might make use of
computer programming.

As you watch, ask your self some questions:
1. How would you like to use computer programming? The answer to this can help you figure out what languages you should learn. One common answer is to learn web develpment. In that case, a new web developer should learn HTML, [[https://www.javascript.com][JavaScript]], and CSS. People who are interested in automating tasks could consider the wildly-popular [[https://www.python.org][Python]]. Scientific programmers might want to learn [[https://www.mathworks.com/products/matlab.html][Matlab]] or its open-source clone, [[https://www.gnu.org/software/octave/][Octave]]. Video designers or animators may be interested in Python and [[https://www.blender.org][Blender]]. Game designers might want to learn C#. iOS developers should learn Swift, and mobile apps may be written in numerous other languages, like Python or JavaScript.
2. What opportunities can you find or create to help you earn income from computer programming? It is helpful to have a goal in mind to help focus and direct your learning efforts. 

* Resoruces for Learning

** Videos
There are great tips here on what it takes to teach yourself programming. Watch these videos to help you figure out where you can go with programming and what opportunities you want to pursue/create for yourself.
- Sylvester Morgan
  - [[https://youtu.be/iIfZV43j4UU][How to Teach Yourself Code (Specific Steps)]]
  - (Advanced discussion) [[https://youtu.be/_1wv7b_kHKk][Become a developer - must know topics for developers without a CS degree]]
  - [[https://youtu.be/HX6ckeZYQDg][Coding Bootcamp vs Degree vs Self-Taught (Best Method To Become A Developer?)]]
- TEDxRainer: [[https://youtu.be/FpMNs7H24X0]["Computer science is for everyone", Hadi Partovi]]
- [[https://youtu.be/THSSHUfSZjc]["How can I make a career change to programming?"]]
- [[https://youtu.be/62tsiY5j4_0]["My Story of Being a Self Taught Programmer ..."]]
- [[https://youtu.be/g9-OS0Pbg4I]["How To Transition Into Software Development ... From A ... Different Field"]]
- [[https://youtu.be/qZKvZzRynLE]["How To Teach Yourself to Code (ft. Quincy Larson)"]].



** Practice/Learn Computer Programming
-  [[https://studio.code.org/courses][Learn Computer Science]] from [[https://code.org][code.org]]. This is the link to their "courses" home. There are numerous activities for people of all ages and skill levels. I've never tried, these, but based on your interest, I might recommend:
  - [[https://code.org/educate/weblab][weblab]] for Grades 7-9.
